###### Tóm tắt file được điểm cao nhất hiện tại: 0.27982
- Xử lý dữ liệu trên python 
+ Clean các dữ liệu
+ Không xử lý maCv
+ Tạo field_7 len và không drop field 7 
+ Gộp 2 biến tuổi 
- Đưa vào chạy trên R

In [1]:
#import dữ liệu 
import numpy as np
import pandas as pd

train_df = pd.read_csv('data/train.csv')
test_df = pd.read_csv('data/test.csv')

total_df = pd.concat([train_df, test_df])

D:\Users\Admin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (51) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
D:\Users\Admin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (50) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

# Data Processing

In [2]:
#### Dữ liệu không đồng nhất
#xử lý biến "province"
total_df.replace('Tỉnh Hòa Bình', 'Tỉnh Hoà Bình', inplace=True)
total_df.replace('Tỉnh Vĩnh phúc', 'Tỉnh Vĩnh Phúc', inplace=True)

#xử lý biến maCv bị lẫn dữ liệu số
total_df.maCv.replace(['0','7','2253','15097','135','147','2853','2983','4999','5339','8059','10958','1006481','1006694','1020883','1020096','17169','275744'],np.nan,inplace = True)

#xử lý FIELD_12 bị lẫn dữ liệu chữ
total_df.FIELD_12.replace(['DN','GD','TN','HT','DN','XK','DT','DK'],np.nan,inplace = True)

# Xử lý FIELD_9 bị lẫn dữ liệu số 
total_df.FIELD_9.replace(['75','74','80','86','79'],np.nan,inplace = True)

# Xử lý FIELD_13 bị lẫn dữ liệu số 
total_df.FIELD_13.replace(['0','4','8'],np.nan,inplace = True)

# Xử lý FIELD_39 bị lẫn dữ liệu số 
total_df.FIELD_39.replace(['1'],np.nan,inplace = True)

#Xử lý FIELD_40 bị lẫn dữ liệu loại khác
total_df.FIELD_40.replace(['02 05 08 11','05 08 11 02','08 02'],np.nan,inplace = True)

#Xử lý FIELD_43 bị lẫn dữ liệu số 
total_df.FIELD_43.replace(['0','5'],np.nan,inplace = True)

# Xử lý FILED_45 không đồng nhất kiểu dữ liệu 
total_df.FIELD_45.replace({'1': 1,'2':2,'3':3}, inplace = True)

# đồng nhất dữ liệu True, False
map_true = ['True', 'TRUE']
total_df.replace(map_true, True, inplace = True)
map_false = ['False', 'FALSE']
total_df.replace(map_false, False, inplace = True)
# đồng nhất dữ liệu đưa Nan, na, nan về np.nan
total_df.replace('NaN', np.nan,inplace = True)
total_df.replace('nan', np.nan, inplace=True)
total_df.replace('na', np.nan, inplace=True)

In [ ]:
# ##### Xử lý maCV
# total_df.maCv.str.lower()
# total_df.maCv.replace('cụng nhõn ki?m hàng', 'công nhân kiểm hàng', inplace = True)
# total_df.maCv.replace('nhõn viờn kinh doanh', 'nhân viên kinh doanh', inplace = True)
# total_df.maCv.replace('cụng nhõn sản xuất', 'công nhân sản xuất', inplace = True)
# total_df.maCv.replace('cộng nhân sơn ip', 'công nhân sơn ip', inplace = True)
# total_df.maCv.replace('undefined', np.nan,inplace = True)

# search_values01 = ['giáo viên', 'cán bộ', 'cb', 'gv','gíao viên','trường th thanh hưng', 'giảng viên','giỏo viờn']
# search_values02 = ['bs','bác sỹ','bác sĩ','y','điều dưỡng','điều dưỡng', 'hộ lý','hộ sinh','dược','dựoc sỹ']
# search_values03 = ['trợ lý','trung cấp','thư ký']
# search_values04 = ['kỹ sư','kỹ thuật','kcs','lập trình','kĩ thuật','ktv','thiết kế']
# search_values05 = ['giám đốc','điều hành','operator','quản đốc','ql','gđốc', 'chủ tịch', 'quản lý', 'quản lí']
# search_values06 = ['kế toán','hướng dẫn','kiểm tra']
# search_values07 = ['lái xe','tài xe','tài xế','lỏi xe','tài xe']
# search_values08 = ['Bí thư','phó chánh','phó chủ quản','phó khoa','cán sự','bí tư']
# search_values09 = ['tổ phó','phó phòng','tổ trưởng','đội trưởng', 'tổ trường','trưởng phòng','nhóm trưởng','trưởng ca','trạm trưởng']
# search_values10 = ['thợ','phụ']
# search_values11 = ['cấp dưỡng','bảo mẫu', 'chăm sóc', 'cấp dưỡng','nấu', 'Cấp Dưỡng','cô nuôi','bm','bếp']
# search_values12 = ['bảo vệ','đội viên cảnh vệ','bvệ','an toàn viên']
# search_values13 = ['lao động', 'đóng gói','lđpt','bốc xếp','tạp vụ', 'lđ']
# search_values14 = ['sale assistant','trưởng nhóm bán hàng','bán hàng','kinh doanh', 'sales association','bhàng']
# search_values15 = ['hiệu trưởng','hiệu phó']
# search_values16 = ['tiếp viên','diễn viên']
# search_values17 = ['kiểm soát','giao dịch viên','thống kê','quỹ','ngân','văn thư','thủ quĩ']
# search_values18 = ['nhân viên','nv','nhan vien', 'n.v','n.viên', 'nhâ viên','nhân viêm']
# search_values19 = ['công nhân','cn','cong nhan','c.n', 'c.nhân','cao','Coõng nhaõn','khai']

# def replace(df,list_val, target_val):
#     df.loc[~df.maCv.isna() & df.maCv.str.lower().str.contains('|'.join(map(str.lower, list_val))),'maCv'] = target_val
#     return df

# for i in range(1, 19):
#     total_df = replace(total_df,globals()[f'search_values{i:02d}'],f'cv_{i:02d}')

# common_cvs = total_df.maCv.value_counts()[total_df.maCv.value_counts()  >100].index.tolist()
# total_df.loc[~total_df.maCv.isna() & ~total_df.maCv.isin(common_cvs),'maCv']='other'

In [3]:
#xử lý biến tuổi
#Vi du lieu tuoi source2 nhieu hon source1 nen fill tu source 1 sang source2
#Cac gia tri duoi 18 cho ve bang nan
total_df['age']=total_df['age_source2'].mask(pd.isnull, total_df['age_source1'])
total_df.age[total_df.age<18] = np.nan
total_df.drop(["age_source1", "age_source2"], axis = 1, inplace = True)

D:\Users\Admin\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [4]:
# FIELD 7:
import ast

total_df['FIELD_7_ISNA'] = total_df.FIELD_7.isna()
total_df.FIELD_7.fillna('[]', inplace=True)
total_df.FIELD_7 = total_df.FIELD_7.map(ast.literal_eval)

# # Tạo cột đếm số lượng phần tử
total_df['FIELD_7_len'] = total_df.FIELD_7.str.len()

total_df.loc[total_df.FIELD_7_ISNA,'FIELD_7_len'] = np.nan

total_df.drop("FIELD_7_ISNA",axis=1,inplace=True)
#total_df.drop("FIELD_7", axis=1, inplace=True)

In [5]:
total_df.FIELD_7

0                      []
1            [GD, GD, TE]
2            [DN, HN, DN]
3                [CH, TQ]
4                [SV, GD]
               ...
19995            [DN, DN]
19996                  []
19997                  []
19998    [TE, DN, DK, TE]
19999                  []
Name: FIELD_7, Length: 50000, dtype: object

In [6]:
##### replace None = -1 và nan = -999 
total_df.replace('None',-1, inplace=True)
total_df.replace(np.nan, -999, inplace = True)

In [6]:
total_df

,id,label,province,district,maCv,FIELD_1,FIELD_2,FIELD_3,FIELD_4,FIELD_5,...,FIELD_50,FIELD_51,FIELD_52,FIELD_53,FIELD_54,FIELD_55,FIELD_56,FIELD_57,age,FIELD_7_len
0,0,0.0,NaN,NaN,NaN,1,1.0,2547.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,1,0.0,Tỉnh Đồng Nai,Thành phố Biên Hòa,None,1,0.0,-1.0,1.0,1.0,...,29.77,17.561,30.955,31.171,0.0,0.04,0.0,0.0,44.0,3.0
2,2,0.0,Tỉnh Đồng Nai,Huyện Long Thành,Công nhân,0,1.0,3273.0,1.0,4.0,...,29.77,56.512,30.955,31.171,0.0,0.16,0.0,0.0,30.0,3.0
3,3,0.0,Tỉnh Tuyên Quang,Thành phố Tuyên Quang,NaN,0,1.0,3991.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.0,2.0
4,4,0.0,Thành phố Hồ Chí Minh,Quận 1,None,0,1.0,1450.0,0.0,2.0,...,29.77,13.789,30.955,31.171,0.0,0.03,0.0,0.0,21.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,49995,NaN,Tỉnh Trà Vinh,Huyện Càng Long,Công nhân thủ công,1,1.0,1443.0,0.0,3.0,...,29.77,47.047,30.955,31.171,0.0,0.14,0.0,0.0,39.0,2.0
19996,49996,NaN,NaN,NaN,NaN,1,1.0,2898.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
19997,49997,NaN,NaN,NaN,NaN,1,1.0,1450.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
19998,49998,NaN,Tỉnh Thái Nguyên,Huyện Định Hóa,None,1,1.0,2176.0,2.0,2.0,...,29.77,57.187,30.955,31.171,0.0,0.16,0.0,0.0,26.0,4.0
19999,49999,NaN,NaN,NaN,None,1,1.0,353.0,0.0,0.0,...,29.77,35.927,30.955,31.171,0.0,0.12,0.0,0.0,29.0,0.0

Xử lý Numerical Features

In [8]:
#Bien Field 3 quan trọng nên sẽ xử lý nan va -1
#Gia tri -1 thì đưa về nan
#Sau do thay toan bo nan ve gia tri median
# total_df.FIELD_3.replace(-1,np.nan,inplace = True)
# total_df.FIELD_3.fillna(total_df.FIELD_3.median(), inplace = False)

# #Fill nan tai bien Field_22 bang median
# total_df.FIELD_22.fillna(total_df.FIELD_22.median(), inplace = True)

# #Fill nan tai bien age bang mean, khong dung median 
# total_df.age.fillna(total_df.age.mean(), inplace = True)

In [7]:
total_df.drop(['FIELD_32'], axis = 1, inplace = True)

In [8]:
train_2403_4 = total_df[total_df['id'] < 30000]
test_2403_4 = total_df[total_df['id'] >= 30000].drop(columns=['label'])
train_2403_4.to_csv('train_2403_4.csv', index =False)
test_2403_4.to_csv('test_2403_4.csv', index =False)

In [ ]:
##### Code R
#install.packages('tidyverse')
library(tidyverse)
# Load data: 
df_train <- read_csv("train_16_3.csv")
df_train %>% mutate_if(is.character, function(x) {str_to_upper(x)}) -> df_train

df_test <- read_csv("test_16_3.csv")

df_test %>% 
  mutate_if(is.character, function(x) {str_to_upper(x)}) %>% 
  mutate(FIELD_36 = as.logical(FIELD_36)) -> df_test
#install.packages('scorecard')
# Conduct binning variables: 
library(scorecard)
#install.packages("magrittr") # package installations are only needed the first time you use it
#install.packages("dplyr")    # alternative installation of the %>%
library(magrittr) # needs to be run every time you start R and want to use %>%
library(dplyr)
# Generates optimal binning for all variables/features: 
bins_var <- woebin(df_train %>% select(-id), y = "label", no_cores = 8, positive = "label|1",check_cate_num = FALSE)
1
# IV for variables/features: 
do.call("rbind", bins_var) %>% 
  as.data.frame() %>% 
  filter(!duplicated(variable)) %>% 
  rename(iv_var = total_iv) %>% 
  arrange(iv_var) %>% 
  mutate(variable = factor(variable, levels = variable)) -> iv_values
# Features have IV >= 0: 
iv_values %>% 
  filter(iv_var >= 0) %>% 
  pull(variable) %>% 
  as.character() -> var_IV_10
# Conduct data transformation based on IV/WoE and filter features with IV > 0.1: 
train_woe <- woebin_ply(df_train %>% select(-id), bins_var) %>% 
  as.data.frame() %>% 
  select(c("label", paste0(var_IV_10, "_", "woe")))
# Data transformation for actual test data: 
test_woe <- woebin_ply(df_test %>% select(-id), bins_var) %>% 
  as.data.frame() %>% 
  select(paste0(var_IV_10, "_", "woe"))
# A function imputes NA observations: 
replace_na_categorical <- function(x, y) {
  
  y %>% 
    table() %>% 
    as.data.frame() %>% 
    arrange(-Freq) -> my_df
  
  n_obs <- sum(my_df$Freq)
  
  pop <- my_df$. %>% as.character() %>% as.numeric()
  
  set.seed(29)
  
  x[is.na(x)] <- sample(pop, sum(is.na(x)), replace = TRUE, prob = my_df$Freq)
  
  return(x)
}
# Use the function: 
test_woe %>% 
  mutate(FIELD_13_woe = replace_na_categorical(FIELD_13_woe, train_woe$FIELD_13_woe)) %>% 
  mutate(maCv_woe = replace_na_categorical(maCv_woe, train_woe$maCv_woe)) %>% 
  mutate(district_woe = replace_na_categorical(district_woe, train_woe$district_woe)) %>% 
  mutate(FIELD_7_woe = replace_na_categorical(FIELD_7_woe, train_woe$FIELD_7_woe)) %>% 
  mutate(FIELD_7_len_woe = replace_na_categorical(FIELD_7_len_woe, train_woe$FIELD_7_len_woe)) %>% 
  mutate(FIELD_41_woe = replace_na_categorical(FIELD_41_woe, train_woe$FIELD_41_woe)) %>% 
  mutate(FIELD_10_woe = replace_na_categorical(FIELD_10_woe, train_woe$FIELD_10_woe)) %>% 
  mutate(FIELD_39_woe = replace_na_categorical(FIELD_39_woe, train_woe$FIELD_39_woe)) %>% 
  mutate(FIELD_11_woe = replace_na_categorical(FIELD_11_woe, train_woe$FIELD_11_woe)) %>% 
  mutate(FIELD_9_woe = replace_na_categorical(FIELD_9_woe, train_woe$FIELD_9_woe)) %>% 
  mutate(FIELD_12_woe = replace_na_categorical(FIELD_12_woe, train_woe$FIELD_12_woe)) -> test_woe_imputed
# Attempt 4: Default Random Forest with Scaled Data
#======================================================
# For convinience, convert binary target variable to factor: 
train_woe %>% 
  mutate(label = case_when(label == 1 ~ "Bad", TRUE ~ "Good")) %>% 
  mutate(label = as.factor(label)) -> df_forGBM 
# Scale our data: 
df_forGBM %>% 
  mutate_if(is.numeric, function(x) {(x - min(x)) / (max(x) - min(x))}) -> df_forGBM_Scaled
test_woe_imputed %>% 
  mutate_if(is.numeric, function(x) {(x - min(x)) / (max(x) - min(x))}) -> df_test_Scaled

# Train Random Forest: 
#install.packages("ranger")
library(ranger)
RF_default <- ranger(label ~ ., data = df_forGBM_Scaled, probability = TRUE)
# Use the RF Classifier for predicting PD (Probability of Default): 
pd_sub_RF <- predict(RF_default, df_test_Scaled, type = "response")
# Save results for submission: 
pd_sub_RF$predictions %>% as.data.frame() %>% pull(Bad) -> pd_sub_RF
df_sub <- data.frame(id = 30000:49999, label = pd_sub_RF)
write_csv(df_sub, "submission03_RandomForest_ScaledData.csv")